### ISSUE TITLE
Publish rxjs6 compatible version

### ISSUE THREAD

**Issue by matiboy** [Jack-Overflow/rxjs-http-client#19]
It looks like the update to rxjs 7 happened only 20+ days ago; could the old version (1.5.4 I think) remain published on npm?
Though rxjs 7 is the stable version now, our project can't be migrated yet it would be nice to use this library.

Thank you

**Comment by Jack-Overflow** [comment]
Hi, all previous versions of rxjs-http-client will remain published on NPM.

Thanks.
