### ISSUE TITLE
ESM related error message on runtime ("Cannot use import statement outside a module")

### ISSUE THREAD

**Issue by philzartis** [Jack-Overflow/rxjs-http-client#23]
Hey there,

I've compiled my project with the following tsconfig:
```
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ESNext"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "types": ["node"],
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "rootDir": "src",
    "outDir": "build",
    "noEmit": false,
    "noEmitOnError": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,    
    "strict": true,
    "skipLibCheck": true
  }
}
```
`tsc --build` yields no errors, but when running `node build/index.js`, I receive this output:
```
...\node_modules\rxjs-http-client\index.js:1
import 'whatwg-fetch';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

I see there has been some recent ESM development, so most likely is related (although v7.0.5 yields the same issue).

Thanks,
Phil

**Comment by Jack-Overflow** [comment]
Hi,

I've been working around a different bundling solution recently and part of it was removing unneeded dependencies. The import that appears to be throwing the error here is the 'whatwg-fetch' polyfill which is not supported on node and has been removed as of rxjs-http-client version **7.0.7**.  Please update to version 7.0.7 and try again.

Thanks,
Jack

**Comment by philzartis** [comment]
Thanks @Jack-Overflow! Unfortunately I've moved to using @nestjs/axios (I didn't see your prompt response until later), have already refactored my code to accommodate for it, and can't confirm the fix. Hopefully someone else can help confirm, otherwise please feel free to close. Thanks again!
