### ISSUE TITLE
Impossible to compile without "DOM" types 

### ISSUE THREAD

**Issue by MuffinKing-jpeg** [Jack-Overflow/rxjs-http-client#24]
I need to compile the TS file without DOM types (for the backend), but it fails on this package.
![image](https://user-images.githubusercontent.com/58091875/192054346-93d59451-f214-4e6c-883b-aee08857717c.png)

My tsconfig.json:
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "./lib",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2020",
    "module": "ES2020",
    "lib": ["es2020"],
    "esModuleInterop": true
  },

  "types": ["node"],
  "typeRoots": ["../node_modules/@types", "../node_modules/rxjs-http-client/"],
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}

```

**Comment by Jack-Overflow** [comment]
The `dom` lib is a dependency of `rxjs-http-client`. You should either add it to your project (`"lib": ["dom"]` in `tsconfig.json`) or use `skipLibCheck` altogether (not recommended). The library cannot assume in which environment it's going to be used, that is runtime information. Thus, the library depends on the maximum possible scope of types, which includes `dom`.

I'm open to suggestions on how to annotate this better but I think there are no options currently available in TypeScript to have this support without defining all of the fetch API types manually within the project which will be a nightmare to sync up and maintain with future changes.
