### ISSUE TITLE
Intercept Request

### ISSUE THREAD

**Issue by dittuxdev** [Jack-Overflow/rxjs-http-client#7]
hi, is there any way to intercept petitions using this library?

**Comment by Jack-Overflow** [comment]
Hi,

Currently, there is no way of intercepting requests or responses in the library. 
Is the functionality you're requesting similar to Angular's HTTP interceptors: https://angular.io/api/common/http/HttpInterceptor

I will look at implementing this and get back when completed.

Thanks.

**Comment by Jack-Overflow** [comment]
Hi again,

I have added request interceptors to the library as of the latest version, documentation for them can be found [here](https://www.npmjs.com/package/rxjs-http-client#request-interceptors).

Thanks.
